---
functional:
  - Адаптивная верстка.
  - Магазин — это SPA приложение, которое не перезагружает страницу.
  - Пользователь может просматривать каталог товаров, фильтруя их и пользуясь
    постраничным выводом.
  - На странице товара и в каталоге должны быть выведены название, рейтинг, цена
    со скидкой и без.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в
    каталоге.
  - На странице корзины пользователь может удалить товар из корзины, продолжить
    выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Интуитивная навигация: пользователи должны легко и быстро находить нужные разделы и функции.
  - Обновление актуальной информации о наличии товара, акциях, скидках, статусе
    заказа, статусе доставки.
  - Прозрачные условия использования: четкие и понятные правила оформления заказов, оплаты, возврата товаров.
  - Наличие  информации о контактах и способах связи с поддержкой, чтобы
    пользователи могли обращаться за помощью или задавать вопросы.
