---
functional:
  - Пользователь может просматривать каталог товаров, пользуясь постраничным
    выводом.
  - На странице товара и в каталоге должны быть выведены название товара,
    рейтинг, цена со скидкой и без.
  - Пользователь может добавить товар в корзину и продолжить выбирать товары в
    каталоге.
  - Пользователь может добавлять товары в корзину и просматривать содержимое
    корзины.
  - На странице корзины пользователь может удалить товар из корзины, продолжить
    выбирать товары в каталоге, оформить заказ с переходом на страницу оплаты.
  - Пользователь может искать товары по ключевому слову или категории.
  - Пользователь может фильтровать товары.
  - Пользователь может просматривать подробную информацию о товаре.
non-functional:
  - Магазин — это SPA приложение, которое не перезагружает страницу.
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован
    для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть оптимизирован для работы  с большим количеством трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Регистрация и авторизация в интернет-магазине
  - Обновление актуальной информации о наличии товара, акциях, скидках, статусе
    заказа, статусе доставки.
  - Прозрачные условия использования
  - Наличие  информации о контактах и способах связи с поддержкой, чтобы
    пользователи могли обращаться за консультацией.
